version: "3.9"

services:
  blog:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis-data
      - redis-cache
    
  redis-data:
    image: redislabs/redismod
    environment:
      - REDIS_ARGS=--appendonly yes --save ""
    ports:
      - 6379:6379
    volumes:
      - ./:/data
  
  redis-cache:
    image: redis:alpine
    environment:
      - REDIS_ARGS=--port 6378 --protected-mode no --save "" --appendonly no --maxmemory 2mb --maxmemory-policy allkeys-lru
    ports:
      - 6378:6378
    


        

  